name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    environment:
      name: 'Production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/public"            # Where index.html lives
          api_location: "api"          # Azure Functions backend
          output_location: "/public"      # Folder for static assets (can be "/" if prebuilt)

      - name: Inject secrets into Function App
        if: success()
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az login --identity || echo "Skipping identity login (use GitHub OIDC for production)"
            az functionapp config appsettings set \
              --name ${{ secrets.FUNCTION_APP_NAME }} \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --settings \
                ACS_CONNECTION_STRING="${{ secrets.ACS_CONNECTION_STRING }}" \
                ACS_PHONE_NUMBER="${{ secrets.ACS_PHONE_NUMBER }}" \
                AZURE_STORAGE_CONNECTION_STRING="${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}"
